spring:
  profiles: woc
  datasource:
    # MySQL
    dbcp2:
      url: jdbc:mysql://localhost:5330/migration_helper
      username: root
      password: if48SrV7#e
      driver-class-name: com.mysql.cj.jdbc.Driver
    # SQLite
#    dbcp2:
#      url: jdbc:sqlite:db/migration_helper.db
#      username: root
#      password: kylinsql
#      driver-class-name: org.sqlite.JDBC

server:
    port: 8080

migration-helper:
  thread-pool:
    thread-count: 16
  library-identity:
    download-path: jar-download
    cool-down-ms: 3000
  git-repository-analysis:
    repository-path: git-repository
  libraries-io-import:
    project-with-repository-path: db/projects_with_repository_fields-1.6.0-2020-01-12.csv
  lio-jar-parse:
    limit-count: 1000
    extract-version-only: false