spring:
  profiles: local
  datasource:
    # MySQL
    dbcp2:
      url: jdbc:mysql://localhost:3306/migration_helper
      username: root
      password: kylinsql
      driver-class-name: com.mysql.cj.jdbc.Driver
    # SQLite
#    dbcp2:
#      url: jdbc:sqlite:db/migration_helper.db
#      username: root
#      password: kylinsql
#      driver-class-name: org.sqlite.JDBC

logging:
  config: classpath:log4j2.local.yaml

server:
    port: 8080

migration-helper:
  thread-pool:
    thread-count: 4
  library-identity:
    download-path: jar-download
    cool-down-ms: 3000
  git-repository-analysis:
    repository-path: ../
  libraries-io-import:
    project-with-repository-path: db/projects_with_repository.csv
  lio-jar-parse:
    limit-count: 1000
    extract-version-only: false