spring:
  profiles: local
  datasource:
    dbcp2:
      url: jdbc:mysql://localhost:3306/migration_helper
      username: root
      password: kylinsql
      driver-class-name: com.mysql.cj.jdbc.Driver

server:
    port: 8080

migration-helper:
  library-identity:
    download-path: jar-download