spring:
  profiles: woc
  datasource:
    # MySQL
    dbcp2:
      url: jdbc:mysql://localhost:5330/migration_helper
      username: root
      password: if48SrV7#e
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-total: 500
    # SQLite
#    dbcp2:
#      url: jdbc:sqlite:db/migration_helper.db
#      username: root
#      password: kylinsql
#      driver-class-name: org.sqlite.JDBC

logging:
  config: classpath:log4j2.woc.yaml

server:
    port: 8080

migration-helper:
  woc:
    enabled: true
  thread-pool:
    thread-count: 256
    calc-thread-count: 16
  library-identity:
    maven-url-base:
      - https://repo1.maven.org/maven2/
#      - https://app.camunda.com/nexus/content/groups/public/
#      - https://repo.maven.apache.org/maven2/
#      - https://maven.aliyun.com/nexus/content/groups/public/
    download-path: jar-download
  git-repository-analysis:
    repository-path: git-repository
  woc-repository-analysis:
    p2cBase: /da0_data/basemaps/p2cFullQ.
    c2pcBase: /da0_data/basemaps/c2pcFullQ.
    c2bBase: /da0_data/basemaps/c2bFullQ.
    b2fBase: /da0_data/basemaps/b2fFullQ.
    blobIndexBase: /fast/All.sha1o/sha1.blob_
    commitIndexBase: /fast/All.sha1c/commit_
    treeIndexBase: /fast/All.sha1c/tree_
    blobContentBase: /data/All.blobs/blob_
  woc-repo-analysis-job:
    repository-list-file: repositories.csv
  libraries-io-import:
    project-with-repository-path: db/projects_with_repository_fields-1.6.0-2020-01-12.csv
  lio-jar-parse:
    limit-count: 1000
    extract-version-only: false