spring:
  profiles: woc
  datasource:
    # MySQL
    dbcp2:
      url: jdbc:mysql://da1.eecs.utk.edu:5330/migration_helper?serverTimezone=UTC
      username: kylinxyl
      password: if48SrV7#e
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-total: 500
    data:
      mongodb:
        uri: mongodb://migration_helper:HeHMgt2020@da1.eecs.utk:27020/migration_helper?authSource=migration_helper

logging:
  config: classpath:log4j2.woc.yaml

server:
    port: 8080

migration-helper:
  woc:
    enabled: true
    object-enabled: true
  thread-pool:
    thread-count: 12
    calc-thread-count: 1
  library-identity:
    maven-url-base: https://repo1.maven.org/maven2/
    download-path: jar-download
  repository-analysis:
    pom-only: true
  git-repository-analysis:
    repository-path: git-repository
  woc-repository-analysis:
    p2cBase: /da0_data/basemaps/p2cFullR.
    c2pcBase: /da0_data/basemaps/c2pcFullR.
#    c2bBase: /da0_data/basemaps/c2bFullQ.
#    b2fBase: /da0_data/basemaps/b2fFullQ.
    c2taBase: /da0_data/basemaps/c2taFullR.
    blobIndexBase: /fast/All.sha1o/sha1.blob_ # da4 only
    commitIndexBase: /fast/All.sha1c/commit_ # da4 only
    treeIndexBase: /fast/All.sha1c/tree_ # da4 only
    blobContentBase: /data/All.blobs/blob_ # da4 only
  woc-repo-analysis-job:
    repository-list-file: test_data/repositories.csv
  libraries-io-import:
    project-with-repository-path: export/LibrariesIOProjectWithRepositories.csv
  lio-jar-parse:
    data-source: all
    limit-count: 10000
    extract-version-only: false
    extract-dependencies: false
    reverse-order: false
    random-order: false
  dependency-change-pattern-analysis:
    method-change-support-file: export/APISupport.csv
    dependency-seq-file: export/RepositoryDepSeq.csv
  evaluation:
    ground-truth-file: test_data/ground-truth.csv